#!/usr/bin/env bash
set -ueE -o pipefail
cd "$(dirname "$0")"

echo "<config_write $1 ...>"

dir="$1"

for arg in "${@:2}"; do
	value="${arg#*=}"
	key="${arg%=*}"
	echo -n "$value" > "$dir/$key"
done

echo '</config_write>'
