#!/usr/bin/env bash
set -ueE -o pipefail
cd "$(dirname "$0")"

echo ''
echo '<config_write>'
echo ''

for arg in "$@"; do
	value="${arg#*=}"
	key="${arg%=*}"
	echo -n "$value" > "../data/input/$key"
done

echo ''
echo '</config_write>'
echo ''
