#!/usr/bin/env bash
set -ueE -o pipefail
cd "$(dirname "$0")"

echo '<consul_configure>'

# Variables
user="$(cat ../data/input/consul_user)"
group="$(cat ../data/input/consul_group)"
consul_type="$(cat ../data/input/consul_type)"
private_ip="$(cat ../data/input/private_ip)"
loopback_ip="$(cat ../data/input/loopback_ip)"
join="$(cat ../data/input/join)"

# Shared
consul_gossip_key="$(cat ../data/shared/auth/consul_gossip_key)"

# Write configuration files
echo "Writing consul configuration..."
cat > ../data/local/conf/consul.conf <<EOF
[Unit]
Description=consul agent
Requires=network-online.target
After=network-online.target

[Service]
Restart=on-failure
EnvironmentFile=-/etc/sysconfig/consul
ExecStart=/usr/local/bin/consul agent -config-dir=/etc/systemd/system/consul.d
ExecReload=/bin/kill -HUP \$MAINPID
KillSignal=SIGTERM
User=${user}
Group=${group}

[Install]
WantedBy=multi-user.target
EOF

# @todo consider moving to provider retry-join
# https://www.consul.io/docs/agent/options.html#scaleway

# BASE
# "recursors" : [ "1.1.1.1", "1.0.0.1" ],
# https://www.consul.io/docs/agent/options.html#recursors
cat > ../data/local/conf/consul_base.json <<EOF
{
	"encrypt": "${consul_gossip_key}",
	"ports" : {
		"dns": 53,
		"http": 8500,
		"https": -1
	},
	"ui": true,
	"datacenter": "global",
	"data_dir": "/opt/consul/data",
	"bind_addr": "${private_ip}",
	"client_addr": "${loopback_ip}"
}
EOF

# TLS
# https://www.consul.io/docs/agent/encryption.html#rpc-encryption-with-tls
# https://www.nomadproject.io/guides/securing-nomad.html#node-certificates
cat > ../data/local/conf/consul_tls.json <<EOF
{
	"ports" : {
		"dns": 53,
		"http": -1,
		"https": 8500
	},
	"enable_agent_tls_for_checks": true,
	"verify_incoming": true,
	"verify_outgoing": true,
	"verify_server_hostname": false,
	"key_file": "/etc/certs/consul.key",
	"cert_file": "/etc/certs/consul.crt",
	"ca_file": "/etc/certs/consul.ca"
}
EOF

# ORIGIN
cat > ../data/local/conf/consul_origin.json <<EOF
{
	"bootstrap": true,
	"server": true
}
EOF

# MASTER
cat > ../data/local/conf/consul_master.json <<EOF
{
	"server": true,
	"retry_join": ["${join}"]
}
EOF

# SLAVE
cat > ../data/local/conf/consul_slave.json <<EOF
{
	"retry_join": ["${join}"]
}
EOF

# Merge
if test -f /etc/certs/consul.key; then
	echo 'Configuring Consul for TLS...'
	./json_merge \
		../data/local/conf/consul_base.json \
		../data/local/conf/consul_tls.json \
		"../data/local/conf/consul_${consul_type}.json" > ../data/local/conf/consul.json
else
	echo 'Configuring Consul without TLS...'
	./json_merge \
		../data/local/conf/consul_base.json \
		"../data/local/conf/consul_${consul_type}.json" > ../data/local/conf/consul.json
fi

# DNS
echo "Configuring Consul DNS access..."
if grep "1.1.1.1" < /etc/resolv.conf; then
	echo 'nameservers already adjusted'
else
	echo 'adjusting nameservers...'
	resolv_contents="$(cat /etc/resolv.conf)"
	echo -e "nameserver ${loopback_ip}\\nnameserver 1.1.1.1\\nnameserver 1.0.0.1\\n${resolv_contents}" > /etc/resolv.conf
fi
# sudo service networking restart
# systemctl disable NetworkManager
# systemctl enable network
# we can't just do
# sudo echo "nameserver $LOOPBACK_IP" > /etc/resolv.conf
# becasuse /etc/resolv.conf also contains these, which is necessary for scaleway networking perhaps... we could try add them to the consul resolver, but not sure that works
# nameserver 10.1.94.8
# domain cloud.online.net
# search cloud.online.net

echo '</consul_configure>'
