#!/usr/bin/env bash
set -ueE -o pipefail
cd "$(dirname "$0")"

echo '<consul>'

# Install
./service_install consul
./service_configure consul

# Gossip Encryption
consul_type="$(cat ../data/input/consul_type)"
if test "$consul_type" != "slave"; then
	# keyring interaction is not available for clients/slaves, will produce:
	# error: Unexpected response code: 500 (keyring operations must run against a server node)
	echo 'Configuring Gossip Encryption for consul...'
	source ./consul_env
	consul_gossip_key="$(cat ../data/shared/auth/consul_gossip_key)"
	consul keyring -install="$consul_gossip_key"
	consul keyring -use="$consul_gossip_key"
	consul keyring -list
fi

echo '</consul>'
