#!/usr/bin/env bash
set -ueE -o pipefail
cd "$(dirname "$0")"

echo '<consul>'

# Install
./service_install consul
./service_configure consul

# Gossip Encryption
source ./consul_env
echo 'Configuring Gossip Encryption for consul...'
consul_gossip_key="$(cat ../data/shared/auth/consul_gossip_key)"
consul keyring -install="$consul_gossip_key"
consul keyring -use="$consul_gossip_key"
consul keyring -list

echo '</consul>'
