#!/usr/bin/env bash
set -ueE -o pipefail
cd "$(dirname "$0")"

# Variables
consul_version="$(cat ../data/consul_version)"

# Install
./service_download consul "$consul_version"
./service_install consul