#!/usr/bin/env bash
set -ueE -o pipefail
cd "$(dirname "$0")"

echo '<docker>'

echo "Installing Docker..."
sudo yum install -y docker
sudo systemctl enable docker
sudo systemctl start docker

echo '</docker>'
