#!/usr/bin/env bash
set -ueE -o pipefail
cd "$(dirname "$0")"

# include hidden files
shopt -s nullglob dotglob
if test -d "$1"; then
	files=("$1"/*)
	count="${#files[@]}"
	test "$count" -eq 0
else
	exit 0
fi