#!/usr/bin/env bash
set -ueE -o pipefail
cd "$(dirname "$0")"

# Variables
public_ip="$(cat ../data/public_ip)"

# Check latest version, ignore return code
./service_latest "consul" || true
./service_latest "vault" || true
./service_latest "nomad" || true

# Write variables
openssl rand -base64 16 > ../data/consul_gossip_key
openssl rand -base64 16 > ../data/nomad_gossip_key

# Known Hosts
echo ""
echo "adding the new host to known hosts"
ssh-keygen -R "$public_ip"
ssh-keyscan "$public_ip" >> "$HOME/.ssh/known_hosts"
./shred "$HOME/.ssh/known_hosts.old"
