#!/usr/bin/env bash
set -ueE -o pipefail
cd "$(dirname "$0")"

echo "<local_begin $1>"

# Inputs
data_path="$1"

# Notify
if ./command_exists say; then
	say "server allocated, starting setup"
fi

# sudo access
echo 'Requesting sudo access at the start instead of later when you might miss it'
sudo echo 'ok'

# Variables
public_ip="$(cat "$data_path/input/public_ip")"

# Check latest version
./service_latest "consul"
./service_latest "vault"
./service_latest "nomad"

# Known Hosts
echo "removing old keys of the host"
ssh-keygen -R "$public_ip" || echo 'no old keys for the host'
echo "adding new keys for the host"
until ssh-keyscan "$public_ip" >> "$HOME/.ssh/known_hosts"; do
	sleep 10
done
echo "cleaning up"
./shred "$HOME/.ssh/known_hosts.old"
echo 'testing the new connection'
echo 'exit' | ssh -T "root@$public_ip"

echo '</local_begin>'
