#!/usr/bin/env bash
set -ueE -o pipefail
cd "$(dirname "$0")"

# Start
echo ''
echo './local_begin start'

# Variables
public_ip="$(cat ../data/public_ip)"
output_path="$(cat ../data/output_path)"

# Clean output
mkdir -p "$output_path/certs"
mkdir -p "$output_path/terraform"

# Check latest version
./service_latest "consul"
./service_latest "vault"
./service_latest "nomad"

# Known Hosts
echo ''
echo "removing old keys of the host"
ssh-keygen -R "$public_ip" || echo 'no old keys for the host'
echo "adding new keys for the host"
until ssh-keyscan "$public_ip" >> "$HOME/.ssh/known_hosts"; do
	sleep 10
done
echo "cleaning up"
./shred "$HOME/.ssh/known_hosts.old"
echo 'testing the new connection'
echo 'exit' | ssh -T "root@$public_ip"

# Complete
echo ''
echo './local_begin finished'