#!/usr/bin/env bash
set -ueE -o pipefail
cd "$(dirname "$0")"

# Locals
remote_path="/root/cluster"

# Variables
output_path="$(cat ../data/output_path)"
private_key_path="$(cat ../data/private_key_path)"
public_ip="$(cat ../data/public_ip)"
vault_type="$(cat ../data/vault_type)"

echo ""
echo "to access the consul web ui, and ssh into the server use the following:"
echo "ssh -L 127.0.0.1:8500:127.0.0.1:8500 root@$public_ip"
echo "open http://127.0.0.1:8500"

if test "$vault_type" = "origin"; then
	echo ""
	echo "copying outputs and extracting values to $output_path"
	scp -i "$private_key_path" -r "root@$public_ip:$remote_path/outputs/*" "$output_path"
fi