#!/usr/bin/env bash
set -ueE -o pipefail
cd "$(dirname "$0")"

echo '<nomad_configure>'

# Variables
user="$(cat ../data/input/nomad_user)"
group="$(cat ../data/input/nomad_group)"
count="$(cat ../data/input/count)"
nomad_type="$(cat ../data/input/nomad_type)"
private_ip="$(cat ../data/input/private_ip)"
region="$(cat ../data/input/region)"

# Shared
nomad_token="$(cat ../data/shared/auth/nomad_token)"
nomad_gossip_key="$(cat ../data/shared/auth/nomad_gossip_key)"

# https://www.nomadproject.io/docs/agent/configuration/index.html
# https://www.nomadproject.io/guides/cluster/automatic.html
# https://www.nomadproject.io/docs/agent/configuration/consul.html
# https://www.nomadproject.io/docs/vault-integration/index.html
# "bootstrap_expect": $nomad_expect,
echo "Writing nomad configuration..."
cat > ../data/local/conf/nomad.conf <<EOF
[Unit]
Description=nomad agent
Requires=network-online.target
After=network-online.target

[Service]
Restart=on-failure
EnvironmentFile=-/etc/sysconfig/nomad
ExecStart=/usr/local/bin/nomad agent -config=/etc/systemd/system/nomad.d
ExecReload=/bin/kill -HUP \$MAINPID
KillSignal=SIGTERM
User=${user}
Group=${group}

[Install]
WantedBy=multi-user.target
EOF

# BASE
cat > ../data/local/conf/nomad_base.json <<EOF
{
	"data_dir": "/opt/nomad/data",
	"datacenter": "global",
	"consul": {},
	"vault": {
		"enabled": true,
		"create_from_role": "nomad-cluster",
		"token": "${nomad_token}",
		"address": "http://vault.service.consul:8200"
	},
	"bind_addr": "${private_ip}",
	"region": "${region}"
}
EOF

# TLS
# https://www.nomadproject.io/docs/agent/configuration/consul.html
# https://www.nomadproject.io/docs/agent/configuration/vault.html
# @todo look into tls_server_name, allow_unauthenticated, create_from_role
# https://www.nomadproject.io/docs/agent/configuration/tls.html
# https://www.nomadproject.io/guides/securing-nomad.html
cat > ../data/local/conf/nomad_tls.json <<EOF
{
	"consul": {
		"ssl": true,
		"verify_ssl": true,
		"ca_file": "/etc/certs/consul.ca",
		"cert_file": "/etc/certs/consul.crt",
		"key_file": "/etc/certs/consul.key"
	},
	"vault": {
		"enabled": true,
		"create_from_role": "nomad-cluster",
		"token": "${nomad_token}",
		"address": "https://vault.service.consul:8200",
		"ca_file": "/etc/certs/vault.ca",
		"cert_file": "/etc/certs/vault.crt",
		"key_file": "/etc/certs/vault.key",
		"tls_skip_verify": false
	},
	"tls": {
		"http": true,
		"rpc": true,
		"ca_file": "/etc/certs/nomad.ca",
		"cert_file": "/etc/certs/nomad.crt",
		"key_file": "/etc/certs/nomad.key",
		"verify_https_client": true,
		"verify_server_hostname": true
	}
}
EOF


# MASTER
cat > ../data/local/conf/nomad_master.json <<EOF
{
	"server": {
		"encrypt": "${nomad_gossip_key}",
		"enabled": true,
		"bootstrap_expect": ${count}
	}
}
EOF

# SLAVE
cat > ../data/local/conf/nomad_slave.json <<EOF
{}
EOF

# Merge
if test -f /etc/certs/nomad.key; then
	echo 'Configuring Nomad for TLS...'
	./json_merge \
		../data/local/conf/nomad_base.json \
		../data/local/conf/nomad_tls.json \
		"../data/local/conf/nomad_${nomad_type}.json" > ../data/local/conf/nomad.json
else
	echo 'Configuring Nomad without TLS...'
	./json_merge \
		../data/local/conf/nomad_base.json \
		"../data/local/conf/nomad_${nomad_type}.json" > ../data/local/conf/nomad.json
fi

echo '</nomad_configure>'

