#!/usr/bin/env bash
set -ueE -o pipefail
cd "$(dirname "$0")"

echo ''
echo '<nomad>'
echo ''

# Variables
nomad_version="$(cat ../data/input/nomad_version)"

# Install
./service_download "nomad" "$nomad_version"
./service_install nomad

echo ''
echo '</nomad>'
echo ''

