#!/usr/bin/env bash
if test "${BASH_SOURCE[0]}" = "${0}"; then
	echo "${BASH_SOURCE[0]} must be sourced"
	exit 1
fi

if test -f /etc/certs/nomad.key; then
	# https://www.nomadproject.io/guides/securing-nomad.html#node-certificates
	# client.global.nomad for a client node in the global region
	# server.global.nomad for a server node in the us-west region
	export NOMAD_CACERT=/etc/certs/user.ca
	export NOMAD_CLIENT_CERT=/etc/certs/user.crt
	export NOMAD_CLIENT_KEY=/etc/certs/user.key
	# export NOMAD_TLS_SERVER_NAME
fi
