#!/usr/bin/env bash
set -ueE -o pipefail
cd "$(dirname "$0")"

echo "<service_configure $1>"

# Arguments
service="$1"

# Clean
function finish {
	if sudo systemctl is-enabled "$service"; then
		sudo systemctl status "$service" -l
		# determine executable
		# service_exec="$(grep ExecStart < "/etc/systemd/system/$service.service" | sed 's/ExecStart=//')"
		# $service_exec
		# sudo journalctl -u "$service"
		# sudo journalctl -f -u "$service"
	fi
}
trap finish EXIT

# Variables
user="$(cat "../data/input/${service}_user")"
group="$(cat "../data/input/${service}_group")"

echo "Running custom configuration script for $service..."
"./${service}_configure"

echo "Configuring service configuration for $service..."
# service configuration
sudo rm -Rf "/etc/systemd/system/$service.d"
sudo mkdir -p "/etc/systemd/system/$service.d"
sudo mv "../data/local/conf/$service.json" "/etc/systemd/system/$service.d/$service.json"
sudo chmod 0640 "/etc/systemd/system/$service.d/$service.json"
sudo chown "$user:$group" "/etc/systemd/system/$service.d/$service.json"

echo "Injecting service for $service..."
# service specification
sudo rm -Rf "/etc/systemd/system/$service.service"
sudo mv "../data/local/conf/$service.conf" "/etc/systemd/system/$service.service"
sudo chmod 0640 "/etc/systemd/system/$service.service"
sudo chown "$user:$group" "/etc/systemd/system/$service.service"

echo "Reload service daeomon $service..."
sudo systemctl daemon-reload

echo "Enabling service for $service..."
sudo systemctl enable "$service.service"

echo "Starting service for $service..."
sudo systemctl restart "$service"
sleep 2

echo '</service_configure>'
