#!/usr/bin/env bash
set -ueE -o pipefail
cd "$(dirname "$0")"

echo "<service_latest $1>"

# Locals
service="$1"
if test "$#" -eq 2; then
	version="$2"
else
	version=false
fi

# Functions
function fetch_latest_version {
	curl -s "https://releases.hashicorp.com/$1/index.json" | json versions | json -ka | grep -v "beta" | grep -v "rc" | grep -v "alpha" | sort -V | tail -n 1
}

# Fetch
latest_version="$(fetch_latest_version "$service")"

# Check latest version
if test "$version" = false; then
	echo "$service [latest $latest_version] https://github.com/hashicorp/$service/blob/master/CHANGELOG.md"
elif test "$latest_version" = "$version"; then
	echo "$service [current $version] is [latest $latest_version] https://github.com/hashicorp/$service/blob/master/CHANGELOG.md"
elif test "$latest_version" != "$version"; then
	echo "$service [current $version] isnt [latest $latest_version] https://github.com/hashicorp/$service/blob/master/CHANGELOG.md"
fi

echo '</service_latest>'
