#!/usr/bin/env bash
set -ueE -o pipefail

if type shred &> /dev/null; then
	exec="shred"
	args="-u"
elif type "gshred" &> /dev/null; then
	exec="gshred"
	args="-u"
else
	exec="rm"
	args="-Rf"
fi

if test -d "$1"; then
	find "$1" -type f -exec "$exec" "$args" {} \;
	rm -Rfv "$1"
elif test -f "$1"; then
	echo "$exec" "$args" "$1"
	"$exec" "$args" "$1"
else
	echo "no need to shred the path, as it does not seem to exist: $1"
fi
