#!/usr/bin/env bash
set -ueE -o pipefail

if ./command_exists shred; then
	exec="shred"
	args="-u"
elif ./command_exists gshred; then
	exec="gshred"
	args="-u"
else
	exec="rm"
	args="-Rf"
fi

for p in "$@"; do
	if test -d "$p"; then
		find "$p" -type f -exec "$exec" "$args" {} \;
		rm -Rfv "$p"
	elif test -f "$p"; then
		echo "$exec" "$args" "$p"
		"$exec" "$args" "$p"
	else
		echo "no need to shred the path, as it does not seem to exist: $1"
	fi
done

