#!/usr/bin/env bash
set -ueE -o pipefail
cd "$(dirname "$0")"

echo '<tls_enable>'

# Variables
loopback_ip="$(cat ../data/input/loopback_ip)"
private_ip="$(cat ../data/input/private_ip)"
public_ip="$(cat ../data/input/public_ip)"
hostname="$(cat ../data/input/hostname)"

# Reload vault env
source ./vault_env

# =====================================
# TLS Certificates

echo 'Generating TLS certificates...'

# -------------------------------------
# Consul

vault write -format=json pki_int/issue/host common_name="consul.$hostname" alt_names="consul.service.consul,server.global.consul" ip_sans="${private_ip},${loopback_ip},${public_ip}" > ../data/output/vault/pki_int_consul.json
json data.private_key < ../data/output/vault/pki_int_consul.json > ../data/output/cert/consul.key
json data.certificate < ../data/output/vault/pki_int_consul.json > ../data/output/cert/consul.crt
json data.issuing_ca < ../data/output/vault/pki_int_consul.json > ../data/output/cert/consul.ca

# -------------------------------------
# Vault

vault write -format=json pki_int/issue/host common_name="vault.$hostname" alt_names="vault.service.consul,server.global.vault" ip_sans="${private_ip},${loopback_ip},${public_ip}" > ../data/output/vault/pki_int_vault.json
json data.private_key < ../data/output/vault/pki_int_vault.json > ../data/output/cert/vault.key
json data.certificate < ../data/output/vault/pki_int_vault.json > ../data/output/cert/vault.crt
json data.issuing_ca < ../data/output/vault/pki_int_vault.json > ../data/output/cert/vault.ca

# -------------------------------------
# User

# user
vault write -format=json pki_int/issue/host common_name="user.$hostname" > ../data/output/vault/pki_int_user.json
json data.private_key < ../data/output/vault/pki_int_user.json > ../data/output/cert/user.key
json data.certificate < ../data/output/vault/pki_int_user.json > ../data/output/cert/user.crt
json data.issuing_ca < ../data/output/vault/pki_int_user.json > ../data/output/cert/user.ca

# -------------------------------------
# Move certificates

cp -v ../data/output/cert/* /etc/certs

# =====================================
# Restart Services

echo 'Reconfiguring services...'
./service_configure consul
./service_configure vault
sleep 5

echo 'Checking Consul...'
source ./consul_env
consul info

echo 'Reunsealing Vault...'
./vault_unseal

echo 'Checking Vault...'
source ./vault_env
vault status

echo '</tls_enable>'