#!/usr/bin/env bash
set -ueE -o pipefail

echo "<tls_add $1>"

# https://github.com/balupton/dotfiles/blob/master/.scripts/commands/cert

# Inputs
base_path="$1"
name="$(basename "$base_path")"

# Locals
pass="$(openssl rand -base64 16)"
cert_file="$base_path.crt"
ca_file="$base_path.ca"
key_file="$base_path.key"
bundle_file="$base_path.p12"

# Actions
echo "creating $name pki bundle"
openssl pkcs12 -export -CAfile "$ca_file" -inkey "$key_file" -in "$cert_file" -password "pass:$pass" -out "$bundle_file"
echo "removing old $name pki bundle from system"
echo '!!! ENTER YOUR OPERATING SYSTEM PASSWORD IN THE PROMPT BELOW TO CONTINUE !!!'
sudo echo 'ok'
subject="$(openssl x509 -subject -in "$cert_file" -noout | sed 's/.*CN=//')"
sudo security delete-identity -c "$subject" || echo "old bundle doesn't exist in system - ok"
echo "adding $name pki bundle to keychain"
sudo security import "$bundle_file" -P "$pass"
echo "trusting $name cert"
sudo security add-trusted-cert -d -r trustAsRoot "$cert_file"
echo "trusting $name cert authority"
sudo security add-trusted-cert -d -r trustAsRoot "$ca_file"
echo "setting $name usage preference"
sudo security set-identity-preference -c "$subject" -s "https://$subject"

echo '</tls_add>'
