#!/usr/bin/env bash
set -ueE -o pipefail
cd "$(dirname "$0")"

echo ''
echo '<vault>'
echo ''

# Variables
vault_version="$(cat ../data/input/vault_version)"

# Install vault
./service_download "vault" "$vault_version"
./service_install vault

# Initialise vault, which initialises TLS, so reload everything
./vault_init

echo ''
echo '</vault>'
echo ''
