#!/usr/bin/env bash
set -ueE -o pipefail
cd "$(dirname "$0")"

echo '<vault>'

# Install vault
./service_install vault
./service_configure vault

# Initialise vault
./vault_init
# curl --cacert /etc/certs/vault.ca --cert /etc/certs/vault.crt --key /etc/certs/vault.key "https://${private_ip}:8200"

echo '</vault>'
